# Generated by Django 3.1 on 2020-12-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201214_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='mime',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
