# Generated by Django 3.1.4 on 2020-12-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201216_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='api.tag'),
        ),
    ]
