# Generated by Django 3.1.4 on 2020-12-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201216_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='images', to='api.Tag'),
        ),
    ]
