# Generated by Django 3.1.4 on 2020-12-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201222_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(related_name='images', to='api.Tag'),
        ),
    ]
